spring:
  application:
    name: qbe
  datasource:
    url: jdbc:postgresql://localhost:5432/employees
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  second-datasource:
    url: jdbc:mysql://localhost:3307/notes
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.testcontainers: INFO
management:
  endpoints:
    web:
      exposure:
        include: health,info
